### ISSUE TITLE
Expose encodeValue

### ISSUE THREAD

**Issue by andig** [go-logfmt/logfmt#14]
I'm using `go-kit/log` and need to redact log entries, i.e. remove usernames, passwords etc. For this purpose I'd like to pass the keyVals through a redact function. Since loggers are stacked, the removal must happen at the time log data is produced, not when it's written (i.e. can't do what in the `io.Writer`). Since keyVals can be any interface, it would be great to reuse logfmts encoding to `[]byte/string` before passing the value to redaction.

**Comment by ChrisHines** [comment]
Do you mean this function:

https://github.com/go-logfmt/logfmt/blob/2fe45f2cf057d707c50bc1949e25ec2cd6b7a015/encode.go#L197

**Comment by andig** [comment]
Thanks for the quick response @ChrisHines. I need a cut-down version of the `encode` function, for context see https://github.com/evcc-io/evcc/pull/2002/files#diff-f8d40abb8d44ed29860274a81a1e9b007ef97669fad4d6296e12975f846caa46R37. After looking at the apis of `writeValue` and `safe...` it feels better at this point to just duplicate the code. Doesn't seem like it is obviously suitable for public api.
