### ISSUE TITLE
drops records that do not follow rules for key

### ISSUE THREAD

**Issue by DanGrady** [go-logfmt/logfmt#3]
Have the logger produce a record even if the key does not follow rules so at least the value is logged lost. Some possible solutions:

1. change the key to "invalid_key" or something similar
2. remove all invalid characters from key so "the key" becomes "thekey"
3. replace all invalid characters 
    with underscores so "the key" become "the_key"
   with hex values with surrounding underscores so "the:key" becomes "the_3A_key" 
   or  include an x "the_x3A_key".

**Comment by ChrisHines** [comment]
@DanGrady I must apologize for directing you file this issue on the wrong project. This package provides the tools necessary to handle invalid keys. The behavior you describe is a result of how the logfmt logger in github.com/go-kit/kit/log is implemented. Could you please move this issue to the go-kit repository and we'll address it there. Again, sorry for the confusion.

**Comment by DanGrady** [comment]
Ok, I am find with closing the issue.
